# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Блог Константина Моренко
email: konstantin@konstantin-morenko.com
description: > # this means to ignore newlines until "baseurl:"
  Блог обо всём, что интересует меня самого, но может заинтересовать и других.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://konstantin-morenko.local" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  kmorengithub

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
# - classifier-reborn
exclude:
  - Gemfile
  - Gemfile.lock
  
# include: [".htaccess"] # default
# lsi: true
# incremental: true # could break building

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # for posts or another collection of files
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"

# MULTILANGUAGE
# languages: ["en", "ru"]
# default_lang: "ru"
# exclude_from_localization: ["javascript", "images", "css"]
# parallel_localization: true