- title: Методические указания к выполнению курсовой работы по дисциплине "Стратегии коммерциализации инноваций"
  link: https://konstantin-morenko.github.io/cw-innovations/
  desc: Методические указания для магистрантов
- title: Отзыв научного руководителя по результатам педагогической практики
  link: https://konstantin-morenko.github.io/ped-practice-review/
  desc: Форма отзыва для оценки результатов практики аспирантов
- title: Программа кандидатского экзамена по специальности 05.14.08
  link: /education/051408-phd-exam-program.doc
  desc: >-
    Программа-минимум кандидатского экзамена по специальности 
    05.14.08 «Энергоустановки на основе возобновляемых видов энергии»
    по техническим наукам (2007)
